### ISSUE TITLE
Broken Master

### ISSUE THREAD

**Issue by marco-neumann-by** [JDASoftwareGroup/kartothek#400] opened 2021-02-03 08:44 UTC
Master is broken due to some bug in pandas 1.2.1, namely that the following code fails:

```python
import numpy as np
import pandas as pd

pd.Series(["Ö"], dtype=np.unicode_)
```

The bug is NOT present on pandas master however and I think it might have been fixed by https://github.com/pandas-dev/pandas/pull/39484 .

**Comment by fjetter** [comment] 2021-02-03 09:00
Duplicate of https://github.com/JDASoftwareGroup/kartothek/issues/396 I believe

xref https://github.com/JDASoftwareGroup/kartothek/pull/399

**Closed by fjetter** 2021-02-03 09:00 UTC
