### ISSUE TITLE
Incorrect indices error when updating cube

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#413] opened 2021-02-16 12:08 UTC
### Problem description
It looks like https://github.com/JDASoftwareGroup/kartothek/pull/398 has broken backwards compatibility for `kartothek.io.**_cube` users

Unit test stacktrace:
```
/tmp/venv/raq/raqbundle/core_data_snapshotter/build_datasets.py:686: in update_cube
    metadata=ktk_cube_metadata,
/tmp/venv/lib/python3.6/site-packages/kartothek/io/dask/bag_cube.py:489: in update_cube_from_bag
    df_serializer=df_serializer,
/tmp/venv/lib/python3.6/site-packages/kartothek/io/dask/common_cube.py:418: in append_to_cube_from_bag_internal
    cube = ensure_valid_cube_indices(existing_datasets, cube)
/tmp/venv/lib/python3.6/site-packages/kartothek/io/dask/common_cube.py:75: in ensure_valid_cube_indices
    compatible_indices = _ensure_compatible_indices(ds, table_indices)
/tmp/venv/lib/python3.6/site-packages/kartothek/io_components/utils.py:125: in _ensure_compatible_indices
    f"Incorrect indices provided for dataset.\n"
E   ValueError: Incorrect indices provided for dataset.
E   Expected: []
E   But got: {'XXX', 'YYY'}

```

**Comment by fjetter** [comment] 2021-02-16 14:44
Do you have a minimal example? this is otherwise impossible to reproduce

**Comment by lr4d** [comment] 2021-02-17 08:43
Of course, I'll post a minimal example today. I just wanted to create the issue already to link to it

**Comment by stephan-hesselmann-by** [comment] 2021-02-19 22:36
The issue occurs when updating a cube that has been created with multiple datasets. The problem is with `ensure_valid_cube_indices` - it mutates the required indices while depending on the unmutated value when looping over the datasets. It should be relatively straight forward to fix. I'll check whether there were more issues on Monday and provide a fix for this one.

**Closed** 2021-02-23 10:24 UTC
Labels: bug
